name: Generate Snake Game

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    - cron: '38 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate Snake Game
      uses: Platane/snk@v3
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          github-snake.svg
          github-snake-dark.svg?palette=github-dark
